site_name: Machine Learning
copyright: Luke Miloszewski

repo_name: lukemiloszewski/machine-learning
repo_url: https://github.com/lukemiloszewski/machine-learning

theme:
  name: material
  font:
    text: DM Sans
    code: DM Mono
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
