site_name: Luke Miloszewski
copyright: Luke Miloszewski

repo_name: lukemiloszewski/machine-learning
repo_url: https://github.com/lukemiloszewski/machine-learning

nav:
  - "index.md"
  - "blog.md"
  - Projects:
    - "projects/resources.md"
  - Python:
    - "python/index.md"
  - Machine Learning:
    - "ml/index.md"

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  font:
    text: DM Sans
    code: DM Mono
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.follow
    # - navigation.sections

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
